### ISSUE TITLE
Welcome!

### ISSUE THREAD

**Issue by mikeal** [iojs/iojs-de#1]
Welcome, new localizations team :)

To get this team up and running you have a few initial tasks to accomplish:
- Create a README.md for this repository, it should include:
  - A "call to action" pointing to the Issue tracker for new translators to find tasks.
  - A list of the team members.
  - Instructions on how to log an issue to be added to this team.
- Set the repository description. This should not be in English, it should be in the language for this community :)
- Social Media
  - Create a twitter account for this language. Share the password privately with the team.
  - Create accounts on other social media popular in this language. Share the passwords private with the rest of the team.
  - Make sure you use these accounts not just to promote newly translated material but also to attract people in your community to help with translation tasks.
- _Optional:_ If you plan to do a Google hangout w/ your localization team have @mikeal add you to the Google+ account so that it can post to the `iojs` YouTube channel. Once you are added there is [documentation on how to setup a hangout-on-air](https://github.com/iojs/io.js/wiki/Meetings:-Creating-a-Hangouts-On-Air-Event).
- Finally, create a new Issue to translate and publish the [latest io.js post](https://medium.com/@iojs). Once translated you should post it wherever you think it will get the most visibility to the community speaking you language, you don't have to post it to Medium unless you think that it is best.

**Comment by ktallett** [comment]
Email/ io.js.de@gmail.com
Twitter/ iojsde

**Comment by ghost** [comment]
how are we going to share passwords? a private http://notepad.cc document or something like that?

**Comment by ktallett** [comment]
unsure never shared a password online before. i was going to suggest an encrypted zip sent via email. I dont know if that is going overboard with security.

**Comment by mthenw** [comment]
@KernTallett @ix you can use https://keybase.io/ to send encrypted message.

**Comment by ghost** [comment]
we should probably go with keybase, yes

**Comment by fhemberger** [comment]
Yes, keybase please. User: fhemberger

EDIT: For posting translations, should we stick to this repo and add a GitHub page with jekyll? Would be much easier to post/edit/update than sharing a medium account with many people.

**Comment by ktallett** [comment]
fhemberger, i noticed on keybase you have an invitation if you could invite me to use and ill send you the password over. If you need my email its kerntallett@gmail.com

Thats a good idea, I think jekyll will be easier yeah.

**Comment by fhemberger** [comment]
@KernTallett Sure, invitation is sent.

**Comment by ktallett** [comment]
thank you, just setting up now. Once you have the twitter pass, if you know of any others twitter names please do welcome them to the group on twitter.

**Comment by ktallett** [comment]
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.1
Comment: https://keybase.io/crypto

wcFMAzvkCtxTXx/mARAAzrfI05mvUeWReWVGuVmvJ7Sm1f4d0aVaY6epfa5cQJcF
aCSJrce5gHc9Vir9N+ygpnvawkAFGMBDehzdq7NLeFd2fPgSqWFedgh4172yCjZb
rsujqO22oXqt8G0qEzw54G2FuateqM8XyM5KSVz45qYVvU3qS8At0AfOHovK8FQ0
4wQuk7erIqqnDdCX1JiTX1wvVcwgISZEUmxaoBg/s+LkRYiGIXZ53p7jvwPYSizr
wEAqASKPGLQQtDxAZ1KXiOk+lRie/QW9j+0uRkZIBQIwDLULkWYKrh2R2WJuApF0
RJl0JJrx7HjBU3YlUp7E08yFAYEJ6u7mQcRj3K9DteYGYB0xQG3ztOxDPJquRWb4
ygX5Z8vOFStSBfDKclvfuU08wsKAmwmbrxRB/P1fRU1AvjwbWCIHSbeclKA/dO+k
eP9k7bGaEBBNLXow+z/lAQNi3peFx4b32yIIueoITchxhz0IisQWfaqZmfA6Fkfc
8xHvLYvkmd6oLdxKVkcdFEfrtGi1qmBtOfIZxzhbwwJ1qNhtyKzDyJ+S8++Gisu/
T5iIPFnj1qXaUEbYJhb0MCLUTleYZj6KFKInoRi7N+SbewZLpLV9pKdUkbGr1kLp
6JDAf1zxkO9+9O1Y7sF0ak+BmO1H3W8Lq/8wr8HoWmwyGQ7VlphpMCc96kV1WibB
wEwDCbjlef9KJIYBB/9rSIUR/90sRDqzC+burP0GrVR9nOY5UhGDIuVqj1vXuDi/
/Gpjr291ZQnv92m2hJ+7+f+jza/Fw7unzxPGCqWDBambu4SemIy7UXdhHAc8ZHYn
Qf5xM68ia+DJdFZ/fJOVoeNDIUobY+GrexXQk0670oyFaol/18TCn1nIZR863F3W
uOMFBH5e9kMoU2MVZe9Y8yfRVEGcAkUPBlbKPx1T1Cm8a+vk9NzEijtRP++XyRrY
mKeNni0XF6UrKOJGjTIxhbLkV+cgzoxP7RAL4+J9OXfjo/yy4q+ru+E9swFBwK3m
SMyOI5VsRlXP+vMEsxBi7sgu9QpHupB4gW1G3OZo0sC7AXWNVINZp1fa744iToKi
+g2Pw8RYP1uCALx797R8cTmtD10UVohuIKFQPnymj58TCxZ5P67fT8Dlc1rQjNCq
Fp1Ytoqkh8ZOc3MDosaIlbB4xV/qCeIeAO0+rVYNBQfDvNmoFcsucLV3Oeo/9QbE
UTZWtP0NCMhq6pc5QMTaT5+ugZr3jdhScSbumG7fNz8LvhFRR5V0r4qd8a4Ri+ov
p6jdRKzej0R9mJs/ptFKEPSTPBen9ttcwroasCTZyru27tGDvBApx0ma6MImL99U
og4D1YMdUSLgtADBi+7BTmJwDtrTJE6qv9VkeBznuF7TOJR/xf5dWXlmg/2BdGYa
UwMW+E7hxiN+/D3Wl+yVqAxzHmj5VEBSfEiIKuJosOyntE07x0uIx7dTiRkXZHNO
bAYDKHityLzTXbXwK7L/Ciarw0+/88B68w1qqG/JAApMO/yrfibbCw7iX7IftyQU
FkYgZbESTNoUIn9Sg8Fbe9WUI0nL2ezh1bfdyw==
=JUW8
-----END PGP MESSAGE-----

**Comment by fhemberger** [comment]
Thanks, worked. In case somebody else needs it: `keybase decrypt <message above> -o <output file>`

I quickly changed the Twitter account's name to **iojs_de** to follow the same pattern as the other translations.

**Comment by ktallett** [comment]
Thanks @fhemberger.

**Comment by ghost** [comment]
decrypting the message via keybase gives me a "the author of this message is unknown to Keybase." error

**Comment by ktallett** [comment]
@ix what is your keybase user name? Ill do again.

**Comment by AlexZeitler** [comment]
If somebody has another invite for keybase, I would appreciate it. E-Mail: alexander.zeitler@pdmlab.com

**Comment by ktallett** [comment]
I'll send you an invite in a mo Alex. Then let me know once you have finished setting up and I will be able to add you as a recipient.  
UPDATE: Invite sent.

**Comment by ghost** [comment]
@KernSTallett ix, like on here

**Comment by ktallett** [comment]
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.1
Comment: https://keybase.io/crypto

wcBMAzCIXYpTyf4eAQgAoyuITWuFJKjMWVtOJoq9BU+DnkxFzA+rqY68AOUMUb7D
LISUR1x3i6ManqPsCfFeewNGAcf3U6btmTKy6kMcNCjhsJv7xX0v0r4XCk+f3A1Z
Gv12R3pD0gb9ThJ8nPdSC+xC0Xw+SNakrIhmFCarq6TooDtoElCzV1T1/Bw/nvFd
9eNS/CKYSst6PqRWnfR+gnZMHrRU3v5Tq/0WHKjjLB58fPMsa0o7/I4+eZiSGICH
UhiCsyFLECYq5VcFB6pzGoYUK4siFVFzSpgH/qneF7u9L4ztFqJ7OH/54WC/1WE2
IorgjjpzCXZT199CdPI2izx+VR0bEt4nA0fBsOwQUcHATAMJuOV5/0okhgEH/iMa
fEntkEGhBaWc2jEKqPHEVXt3P/RBTGZl8KoLZ0GvX67Z1Odp9AWGfhb5BN68Yaqf
GfYIuWWq4cXTUuU7FTHAG2utKlhJeWpJ1MiCnWneYLNkDdd3ALRxSyOwJE6K08Eu
HooI2VV0R8z1umLHAyoKObIchSAw9pafjQGvSzt+TcYINN8rtd2rvGZfxz1KOF2Q
CZP9h0Jz9PXyVA3Sh991xznjod8je8hq7xLQe3/rNPVm27VU9Me5uITivIeMThjC
ojacpAM/t+bhFTdfYjMIraYBTqhRRDzPFDW0aKZe1fPav59raCnRicOOyyI5C6XX
EK2ugE3aXSa6ctRtjcLSwLsBLWuoyNZNdKWRFchaz+JQ+cOGMB8j0SWWfToAbINg
DoXBOzVP1BSIlvP13uUZ/GxqAMHy/Z8o/b2xHDgQkBUOfHf1m3so0F0KFStqKxJ9
gS+l5i+8RMF6P/A65WIuUquihmMVxuv1VYXQMkIshRg19v14dyEiTCIKUgFYJIkj
dfwl3rze6dVV9jyqcJc/dsk2Z61FlNsVPCbkyrl1EtVi1QlXWgpQVu7FaWXtdG5+
VONg3lXZkB4CqH5lLotRsrpLYd0eD5OiyNSgzkpOMKw8dbe5JE+yQyYmwt3X3gtp
+1dloQWv/w5D7f+aa55HRDWeZbvoEEolsXAgN+94AVx8t72K4q43Xd/Ns0arJOGD
JH/R4pZqJ/EBCMQXvklgAhL4479X20l7ftemjq21ejYexrFufrltH4S5Fjg5G1dF
WvozWGF6NSolfSHTfEiyNAZR8e0vXGULhLF+1nu4+ILliJm3n2FKGHlTPlqRy60a
mPf7wheevwDuYlT5
=Z3eC
-----END PGP MESSAGE-----

**Comment by ghost** [comment]
please add me too. denny.trebbin@gmail.com

**Comment by fhemberger** [comment]
Ok, now after the initial team is set up, we should wait for the website team to clarify, how the [website translation workflow is defined and set up](https://github.com/iojs/website/issues/125#issuecomment-73435623), so we don't do the same work twice.

The question is which additional material should be translated (or newly written) for the German community which then will be hosted on our own and will not part of the main `website` project.

**Comment by ghost** [comment]
ye good question.
i think the docs we should translate. and then gather a list of german resources like presentations, videos, meetups. not sure yet if we should maintain a calendar with events happening in german language. what i can not answer yet is the question on what social media channels we should be present. i am usually not tending to read/watch/listen much technical stuff in german language except golem.de and heise.de.

we may can have a chat later.

**Comment by AlexZeitler** [comment]
@fibric Send you an keybase invite (did not finish decrypting the message as I ran into some issues on Ubuntu and won't make it until friday).

**Comment by ghost** [comment]
@AlexZeitler thanks alex.
have a keybase account but gpg failed due to no secret key. i am not sure if i miss something.

**Comment by AlexZeitler** [comment]
Ran in the same issue, verification of GitHub and Twitter went well but could not decrypt the message.

**Comment by ghost** [comment]
i think @KernSTallett has to address us as receptions.

**Comment by ghost** [comment]
yeah.

**Comment by ktallett** [comment]
The following should work for you @fibric 

-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.1
Comment: https://keybase.io/crypto

wcBMAx9o9S6OrAYMAQf+J/xOy0Lk0JPPfqRwAkhNFDEixtqZJPrzR2SMvJY8XLYG
I98eUupULQGRxrxjJcLqIIy3uS5qWPiSq+G2+7zl6lVHnBdbIYPMjyVN24y27J1I
VizCJdY3g9lUzviQyRQi9b//xOyvvIyj4tREyhtlBEzhwh+zsnmTIxJPOKJG9ipL
Kbee/qKxnHXuap0rT5jWaB40ElDnNXd8P24hMvq41xiieShHes8toaZaVsKtfCCb
7XgqYJd3b65Q5I7TXxkdOV/7rj55EaKjIF0QePnl/gUb7kJhMKDBzRMFgdDzjsyr
tRX80mETUQ1Q5E+TcrLOtlzh4pqNPhPy9vHOGeYHXMHATAMJuOV5/0okhgEH/2MU
iurRp772JpBg4pb01q4QtpksQSIo0JmPGpnN4E9XmcdC3ggStcnHYNU+6YgJdHSr
5PkKmuflz68tZy6B+dV4v+1xW6TtOpeD8++hPNcWf4yE/PTpuvBxVOuuSSJF9u4i
UJeBkRXYHoyTyabA/pfrkuoidmFgymK1H5ODKGAAWpybP5uuFRP0Sv4TUzJ7HFNG
q6k8BotpTdPQlvvNDqoNxMoKkDSqA0Fj2VBltyoXOAhUySAPMVys/jVPgczMI61V
KJxlas0eNtCAWC8eqwbWxwzhm5Tse5cDiUtb0krT3SWsCM0HLBRM7D/mwvmfQVrl
I48GJrsalNAm0FDO7YTSwLsBZLDtvbeQGoKt28RmD1PFhPliNh5u3I/76TBjMtUR
ulwGOLuopo1arxt3n/+B7qmtqEgXRCDpX9B2k9vaE828kna7MU19VqRtOY3hy+g0
4zgH9gdL42FTHZbThCkR5zOQbBS1Xwxl08JX3ZCEeQtAe+TrGqd+uHP0LfZGOz1j
1nChKKZLAP6OOzIEw2+TEyW9wlMBqBXG8r0Si5f94KB64SoU88SpuQnA9wbD4TYN
ssK/qvZ2jQ1uJVRsaJy6UdG6JlEKaaP+XfapsfJOOBsR/orsvG29k1yHC7BUytXR
3kX7feHC894znSc8cz7CUB2MZb6ZKVyIm4j+GL+s/dsXxJ0kUpo3hNm/MR31d6js
yoHjM0kr298rn0ETrDkNFl8RP34ADu8yobkf+S9y9ogo0igdP4jPY5vtWuoLLRp9
A5N4f4jgdd6jSPv6Nz/ZG2NiBMxY2igtgunQ4lz31NbInZb8F2e2iWuREmS1Lc4a
OgC7NSmD2ARDr9MC
=KPTf
-----END PGP MESSAGE-----

**Comment by ktallett** [comment]
And for you @AlexZeitler 

-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.1
Comment: https://keybase.io/crypto

wcFMA4ugscjvag/eAQ//ZMUce4WdT5sIL12IXj9GHBHVA0QLWNktnv73rUS8/6GD
obNvsxe+0o/SNW3TveWyATkKT31jvW1+ynXr7HgsngdMaAUwWNvQZOJnOpoO2SiY
Cr4ma37j+McFVieR57fnYr2BLkSC1zGlGjiCHa/6TttLqg4tI7A3UBPiP1nUyIED
xCRFv7pfuWtgv1/RwCCzbc3a3aFDMFLRByJz8XYUMSh7eKaMPLeG10tRS5UObdG+
0bNevJZuxjToCPvmHuJIoBhnlzCKe0uQHmLZ8Wbx37JS6dFzi2ATLrCWeH+kJ1/u
NGTZDaYYaU9BA11yjRtYfFenfk/jCxTn73gfAST9DKKSA69EjWUEo7ov46gGBP/9
d96pDgqZd8smre97p52DlYXiB+CN2bmpD2xkeDqRscblGFc0LlcQU4CoaQGcJNTn
T1TfuqFmir+k3w0vhD08CfU0RhMIQgdGA/l354XFAtzsuJmX+ObFQl9hx5A10QC4
NJiNT1waUSvu/kbX8qGqhCmAig5XcP/04rLox3XQsuY2PUfosoxMP/+XGwib1V5Y
W4g0cCCC00ndtEasFLYk3FvK7FDYhldD8StLipZrQUSqkLuHf5ayWROWquP1xD0Z
J51PSu2qkFdNdngeDaMb8exm3Q5LtoKBHdxmQc7Z/vR4SFhohpF5FtLMQWDHrYrB
wEwDCbjlef9KJIYBCAC6UjH6NA2DvFdq2goAkA0jl+wv1gNSCjjkgu+tlt4y55++
3FcGq11hDPK5+L8ziGo8ZILEqUVkBcwa/gozTnSDZbv0QrgfLsuni8tGpBPanrAu
C++mo6JGVjsMDRJXxwLjha2QQqp87DIYgJuB78akzNfTJbbsY5JiqLfQFBkizHCT
DlLffr8WZEE5r1rrR9kOxZ+TltNWsIBLaB1MtrtW+dY8de69SNCInOyCc4TgBxb2
27tIK37v9XjGPL8+i6VByXwbQQyEn4P4c/MigCvTrMv+E2x2Wk636VAA7PNKbOly
RD2RHQsWMgS+2zhSMVcID6lzAbKYBlOg4GyjVMiI0sC7AZhrtmNu03LyJql40k7h
8PW64n8kHSGsRnIdC/kKSQqJ6sUXID0wH6WJQSOv/c3FOkpy9VbePA4GmGazjH92
6Z1wH4jofaSIzqGRfaockzLfe9/ypffOxJSQo55KfloWj5XJKf+DssfhiwxeAtiX
dSqMfJ3F4xCx07/lKgz3a/puLL2FwvFSoyMYOjC/9kywUhDVpB5EDr89awruj9sd
ES60F9f+TlpqBjs5rrE/TbXu5JEkjqfZXUl4l5AdiJDDqYBLBVaZAX6wkCeetLte
S5RanDlUR2CwxnkzLwbs7B6HVYasyRVvIRooqCdPD6INLvQpJQ1RNbME9LK3hlP9
azQBn/Wz8OuAhBK+ap8jTOBrntZh9r8osflS+G62sa/it6Qjj2HU4WFKa9ZiQzi8
Q1etyA17G3MUg8GsrJbOvgS9fO/B8dg54qYwUE/a2u1PFjLC1OsX3oR3G+/YugRm
dVyxQk2HQWz8UFkQbHqRyyz4ARwsHISIcqORjw==
=TEPA
-----END PGP MESSAGE-----

**Comment by ghost** [comment]
@KernSTallett it works, thank you

**Comment by ktallett** [comment]
I dont feel i am using keybase correctly but i know this method of doing individual encryptions worked for @fhemberger so this should be good for @AlexZeitler and @fibric . If anyone can enlighten me regarding a more efficient way of using keybase that would be great.

**Comment by ghost** [comment]
I think you are using it correctly.
Maybe keybase can be extended to use a list of [them] and not just a single [them] aka recipients.

**Comment by AlexZeitler** [comment]
@KernSTallett works, thanks!

**Comment by ghost** [comment]
I think we can close this issue

**Comment by ghost** [comment]
Github on a smartphone >__<
We have a instruction set about [translation](https://github.com/iojs/website/issues/125#issuecomment-73618886)

**Comment by timaschew** [comment]
I would like to join the team :)

**Comment by ktallett** [comment]
@timaschew I don't know if we have the power to add you. If we do, i don't know how. This is the thread @mikeal said to post on if you are interested in joining. 
https://github.com/iojs/website/issues/125#issuecomment-73914131

Just say +1 and the German translation group and i'm sure he will add you.

**Comment by fhemberger** [comment]
We have the power to add you … gimme a sec. ;)

**EDIT:** Done

```
This repo > Settings > Collaborators > `iojs-de` > Invite and add user to team
```

**Comment by timaschew** [comment]
awesome :+1:  thank you

**Comment by ktallett** [comment]
Thank you for explaining @fhemberger. Useful to know. 

Welcome to the team @timaschew.

**Comment by ChristianGaertner** [comment]
I would like to contribute to the German translation as well and know how and where to contribute exactly.
(I already have experience translating software, being a member of the ubuntu-de translation group for a while now).

**Comment by ghost** [comment]
Hmm, it seems we have lost our admin powers to invite people to join our iojs-de team.
maybe @mikeal has more to say.

**Comment by ghost** [comment]
@ChristianGaertner I have added you as a contributor until someone with more power can add you to our team.
2 weeks ago I have received an email about being promoted to admin group. I still have this tag but I can not invite peoples. Maybe core io.js team has set a team limit. They had a discussion about limits for l18n teams but not sure what the result is.

**Comment by mikeal** [comment]
So, we're on the GitHub beta for new-style permissions. Group admins can add and remove people from their teams _but_ they cannot "invite" people to the org (which really sucks). The only people who can invite to the org are the org admins (which have rights to literally everything). I've promoted a few people to org admins to get around this but we're still quite limited :(

**Comment by ghost** [comment]
thanks for lighten me up :)
we have to blame github as it seems

**Comment by mikeal** [comment]
Ya, there is this strange assumption that adding people to an org should be heavily guarded :(

**Comment by ChristianGaertner** [comment]
Thanks for adding me to the team. I'm happy to be able to contribute to the io.js project!

**Comment by ghost** [comment]
@mikeal what should we do now, after the convergence? is the new node.js website already localized?

**Comment by fhemberger** [comment]
@schisma No, it's not. But we can start translating it into German.
