### ISSUE TITLE
Translation of io.js website

### ISSUE THREAD

**Issue by fhemberger** [iojs/iojs-de#14]
I've started to translate the website into German, reviews appreciated:
https://github.com/iojs/website/pull/171

The ES6 page and the last FAQ paragraph still needs to be translated.

**Comment by fhemberger** [comment]
Does someone want to help with the ES6 page and the last paragraph of the FAQ? Website would be complete then.

**Comment by ktallett** [comment]
I will take a look at the faq again later this afternoon.

Edit/ Please say what you think of the first sentence, i haven't committed it yet as i feel there maybe an error or two. 

Open source-governance befürworten der Gebrauch und der Philosophie von Open-source ermöglichen Abwandlung von ein Endprodukt.

I have been trying to work on rewording the second sentence but that I am finding trickier.

**Comment by fhemberger** [comment]
Hm, still sounds a bit bumpy. I think this last section has to be rephrased completely to be more accessible in German.

**Comment by fhemberger** [comment]
@iojs/iojs-de Can someone please look into the ES6 page and translate it?

**Comment by ktallett** [comment]
Checking out es6 now to see if I can take it on. 

Regarding the open source governance, we need to write straight off in German. 

From my understanding the main point is:

open access and open source allow anybody to edit the final product for their needs and also allows anybody to have input regarding the product. 

Anyone willing to try to get that message across in German?

**Comment by ghost** [comment]
Me. I'll take that try

**Comment by ghost** [comment]
I shall not use Github on my smartphone >__<

**Comment by ktallett** [comment]
Thanks @fibric :+1:

**Comment by ghost** [comment]
here is my take.
can someone read and check for typos please.
https://github.com/fibric/website/blob/master/content/de/es6.md

I have not translated technical terms. And after so many commas in original english version, I have followed them and created to many sub-sentences. Any humanization of my translation is welcome and appreciated :-)

as mentioned from @mikeal at the end of our translation someone other than me must add :+1: as comment. this 4-eyes check is required for official translations. thanks.

**Comment by fhemberger** [comment]
Thanks @fibric for your work, I added some comments and fixes directly [on your commit](https://github.com/fibric/website/commit/6ca40a9fb31bbab26fe211eea32a3489f58949ca). After you have checked on them, let's see we get a :+1: here, so we can merge it for the website.

**Comment by ghost** [comment]
please check and :+1: `io.js-de` below the pr https://github.com/iojs/website/pull/229

**Comment by fhemberger** [comment]
Found a typo and offered an alternative on a different line, otherwise LGTM. :+1:
