### ISSUE TITLE
Unofficial iojs de site

### ISSUE THREAD

**Issue by ktallett** [iojs/iojs-de#17]

**Comment by fhemberger** [comment]
Uhm … yes? I have been briefly talking to @marcofrodl, who already registered iojs.de:
https://twitter.com/iojs_de/status/566231263141715969

The current website is at http://iojs.github.io/iojs-de/ and needs a bit more love. ;)

**Comment by ktallett** [comment]
Ok i took a look. 

In our about section: 

I was thinking of including a brief description regarding the project, then our aims for our site. 
Thoughts? 

Another thought i had was regarding content, native german content and translations of course. What do others think about us accepting submitted articles? Checked by ourselves to make sure no duplication and of a high quality. I understand right now that we may not attract many people for that to be a major way of gaining content.

**Comment by fhemberger** [comment]
Sure, go ahead! I think it's a good idea to also link German tutorials/articles and news about io.js from other sources as well.

**Comment by timaschew** [comment]
I talked to Marco some days ago

my mail:

> Hi, habe gesehen, dass du die Domain iojs.de registriert hast.
> Wie es aussieht, ist die Seite ja noch nicht „richtig“ in Benutzung seit Dezember.
> Falls du sie nicht mehr benötigen solltest, die iojs (https://iojs.org) Community ist bestimmt daran interessiert.

he answered:

> Hallo Anton,
> 
> da wir als Berater häufiger auch bei Node und iojs-Projekten unterstützen, wollen wir unter dieser Domain ein Portal aufbauen. Sie steht also nicht zum Verkauf. Aktuell haben aber - wie so oft - andere Projekte Vorrang. Bist du Contributor für iojs oder warum schreibst du?

**Comment by fhemberger** [comment]
Maybe we can work together on the topic and build up a company agnostic portal for io.js, of cause companies can contribute as well and link to their websites and services.

**Comment by fhemberger** [comment]
@iojs/iojs-de Can you please add your ideas for the German community website? What would you like to see and what would you contribute to it?

At the moment, we have the first of the official io.js posts from Medium, the second one is still waiting for a translation (#13). Should we write additional posts, collect links to other German blog posts/articles/tutorials, etc?

_Personal remark: I myself am much more interested in the translation of the official site, installer, etc. and general website topics than creating/collecting additional resources and blog posts. So if you want to take over the part and start a German community site, please go ahead and do so!_

**Comment by ktallett** [comment]
I feel a curated list of tutorials would be useful. We could fill in the gaps regarding that, if needed.

**Comment by ghost** [comment]
we have a white paper to start with.
no german community page has grown just yet.

**Comment by fhemberger** [comment]
I'm closing this for now because of the upcoming `new.nodejs.org` website, which will include links to tutorials, etc. as well (also localized ones).
