### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by ktallett** [iojs/iojs-de#18]

**Comment by timaschew** [comment]
can you provide some information for this issue? maybe also for #17  
There is already a twitter account, isn't it? https://twitter.com/iojs_de

**Comment by ktallett** [comment]
My main thoughts were: 

Should we be translating all original Twitter posts from iojs Twitter in German? 
If so how would we designate that out.
What other items should we be posting ? 
Is this like an early version of our unofficial site where we can link to important German iojs articles and the like?
Should we have a system so there are no duplicate posts?

**Comment by ghost** [comment]
i could take it upon myself to translate the twitter posts. i'll just set up a column for the iojs user and translate them as they come up.

**Comment by fhemberger** [comment]
Woah, translating all the tweets is way too much. Tweets should include links to new releases/blogposts and own content. Think of it as the tweets for the German community, not 1:1 translations of the original tweets.

If you're using the account to reply to tweets or post own thoughts, please add your initials at the end of the tweet (like ^fh). This helps a lot when people want to know who of the team they've been talking to.

**Comment by timaschew** [comment]
@fhemberger :+1:

**Comment by ktallett** [comment]
I would say looking over the past few days, there is probably a tweet every two days perhaps each day, we need to translate from
iojs. We need to be setting up a way of collecting potential links, articles for both Twitter and our site. An RSS feed? What sites?

**Comment by ghost** [comment]
translating all the tweets is not a good idea. who really cares in what language which post is now available. if we are trying to build up a german io.js scene then it might be enough have changelog and conference call tweets translated. tweets about blog posts on medium are irrelevant because if we translate them then our german blog post tweet is doing the job already.

**Comment by fhemberger** [comment]
Hmm, is anybody interested in keeping the German Twitter account at all? At the moment I seem to be the only one adding some tweets now and then (although they're only retweets of news/releases from the official account or Rod/Chris). And I must admit, I'm currently not that eager to continue to do so.

We don't really have relevant content updates (as we don't translate the Medium posts or create separate news/blog posts in German), so the Twitter account doesn't make much sense at the moment.

**Comment by fhemberger** [comment]
Pinging @nodejs/iojs-de …

**Comment by ghost** [comment]
I can maintain it since I spend a fair amount of time on Twitter anyway.

**Comment by fhemberger** [comment]
It's not so much about maintaining the account (in a technical sense) but creating/linking to original German content regarding io.js – since we're not having regular updates (like the Medium posts), we actually don't have much to tweet about which has not already been posted to @official_iojs yet.

**Comment by fhemberger** [comment]
I will close the Twitter account in the next days, it has already been dormant for over half a year, and the posts it does contain, are merely release-retweets from the main account. If someone wants to take over and _continuously keeps tweeting_ about Node.js in German, let me know, otherwise it will be gone.

Nothing is worse than news accounts without any news …

**Comment by ghost** [comment]
is the handle still iojs_de or did you change it?

On Thu, Oct 8, 2015, at 05:13 PM, Frederic Hemberger wrote:

> I will close the Twitter account in the next days, it has already been
> dormant for over half a year, and the posts it does contain, are
> merely release-retweets from the main account. If someone wants to
> take over and _continuously keeps tweeting_ about Node.js in German,
> let me know, otherwise it will be gone.
> 
> Nothing is worse than news accounts without any news …
> 
> — Reply to this email directly or view it on GitHub[1].

Links:
1. https://github.com/nodejs/nodejs-de/issues/18#issuecomment-146575346

**Comment by fhemberger** [comment]
It's still the old one at the moment, because I'm not the owner of the linked gmail address (and changing the handle should trigger a email confirmation). In case of transferred ownership, that's something I need to figure out. ;)

**Comment by ghost** [comment]
IIRC, changing the handle only requires a password confirmation,
nothing more

On Thu, Oct 8, 2015, at 05:19 PM, Frederic Hemberger wrote:

> It's still the old one at the moment, because I'm not the owner of the
> linked gmail address (and changing the handle should trigger a email
> confirmation). In case of transferred ownership, that's something I
> need to figure out. ;)
> 
> — Reply to this email directly or view it on GitHub[1].

Links:
1. https://github.com/nodejs/nodejs-de/issues/18#issuecomment-146577125

**Comment by ktallett** [comment]
If you need the email I can transfer the account to you. Sorry I haven't
been of more use in this project I started with good intentions yet health
and hospital stays have got in the way and I have been too embarrassed to
get back in touch to restart helping.

**Comment by ghost** [comment]
@ktallett if it's not too much of a hassle, i'd gladly accept it :)

**Comment by fhemberger** [comment]
@schisma Does this mean you want to take over the Twitter account?

@ktallett No need to feel embarrassed, I hope you're okay again, so just chime in whenever you feel like.

**Comment by ghost** [comment]
I still have access to the account and changed it to nodejs_de.
https://twitter.com/nodejs_de

I'm not having the gmail account password, or at least I can not find it in keychain.app.

**Comment by ghost** [comment]
@fhemberger pretty much, yeah.

**Comment by ktallett** [comment]
I have the password I just wish to make sure the email is disconnected from all my accounts but can't actually find the email address. Does anyone know it?

**Comment by fhemberger** [comment]
Pretty sure it is: `io.js.de``@``gmail.com` ;)

**Comment by ghost** [comment]
if you're done, just shoot me an email at `jona@schisma.co` with the password!
