### ISSUE TITLE
formal address 'sie' 'du' or addressless?

### ISSUE THREAD

**Issue by ghost** [iojs/iojs-de#20]
I have one question about formal address.

'In io.js können sie ...'
'In io.js kannst Du...'
'In io.js kann man...'

What is our prefered formal address?

with my voice i'll vote for 'du' because it sounds more friendly and welcoming.

**Comment by ghost** [comment]
yeah, same. i'll go for 'du'

**Comment by ktallett** [comment]
Same here 'du'.

**Comment by timaschew** [comment]
:+1:  du

**Comment by AlexZeitler** [comment]
Du.

**Comment by ghost** [comment]
after 3 weeks, 5 of 8 members have voted for 'Du'.

How to go on now?
I have read our official iojs.org translations we have done and found a nice mixture of everything regarding to formal address.

**Comment by ChristianGaertner** [comment]
I'd vote for "Du" as well (with capital 'D', so it's a bit more formal).

**Comment by ghost** [comment]
I'm just going to close this since there hasn't been activity for a while and all votes are for 'Du' anyways.
