### ISSUE TITLE
Reconciliation Proposal: Voting of iojs-de

### ISSUE THREAD

**Issue by fhemberger** [iojs/iojs-de#21]
@iojs/iojs-de: Please have a look at the discussion over here https://github.com/iojs/io.js/issues/978 about the reconciliation of io.js / node.js and give a short feedback ( at least :+1: / :-1: ), so we can post our vote on this.

For questions or deeper discussion of this topic, please post in the original issue's thread.

**Comment by AlexZeitler** [comment]
:+1:

**Comment by ghost** [comment]
:+1:

**Comment by fhemberger** [comment]
:+1:

**Comment by ghost** [comment]
:+1:
