### ISSUE TITLE
I can help translating

### ISSUE THREAD

**Issue by juliangruber** [iojs/iojs-de#24]
Hey, I'm a native german :)

**Comment by ghost** [comment]
ping @mikeal

**Comment by fhemberger** [comment]
@mikeal Can you please add @juliangruber and @ChristianGaertner to iojs-de?

**Comment by fhemberger** [comment]
@juliangruber At the moment, there is not much translation work required (website is already done), but we definitely will need some help during the merge of the nodejs.org and iojs.org websites. But if you have any ideas for improvement of the translations so far, please let us know (or send a PR).

**Comment by juliangruber** [comment]
ok great, i will! thank you :)
