### ISSUE TITLE
Translation, round two

### ISSUE THREAD

**Issue by ghost** [iojs/iojs-de#26]
nodejs/new.nodejs.org#222

As said there, we need to translate the website contents. How do we want to do this - commit it to this repo first and then open a PR on the website repo, or just directly do that?

**Comment by fhemberger** [comment]
How about creating a new "nodejs-de" branch of the website repo and everybody helping with the translation can fork the project and commit into that branch. Afterwards, it will be merged into master.

The only thing we have to discuss is who is willing to translate which parts:
- [ ] 404.md
- [ ] about/advisory-board/index.md
- [ ] about/advisory-board/members.md
- [ ] about/governance.md
- [ ] about/index.md
- [ ] about/organization.md
- [ ] about/releases.md
- [ ] about/resources.md
- [ ] about/trademark.md
- [ ] about/working-groups.md
- [ ] docs/es6.md
- [ ] docs/faq.md
- [ ] docs/index.md
- [ ] download/index.md
- [ ] download/package-manager.md
- [ ] download/releases.md
- [ ] foundation/announcements.md
- [ ] foundation/in-the-news.md
- [ ] foundation/index.md
- [ ] foundation/members.md
- [ ] foundation/newsletter.md
- [ ] foundation/tsc
- [ ] foundation/tsc/index.md
- [ ] get-involved/code-and-learn.md
- [ ] get-involved/contribute.md
- [ ] get-involved/development.md
- [ ] get-involved/events.md
- [ ] get-involved/index.md
- [ ] index.md
- [ ] security.md
- [ ] site.json

(I deliberately left out the blog posts and TSC minutes.)

**Comment by fhemberger** [comment]
@nodejs/nodejs-de Anyone willing to translate the nodejs.org site to German?

**Comment by juliangruber** [comment]
@fhemberger feel free to assign me 5 to get started

**Comment by fhemberger** [comment]
@juliangruber I'm not assigning anything, pick your own. :smile:

**Comment by juliangruber** [comment]
@fhemberger ok, then shall we create issues for each page?

**Comment by fhemberger** [comment]
Just go ahead and fork the repo and start translating. Add a note here, which pages you're planning to work on (so others don't start working on the same ones), and I'll update my comment above.

**Comment by juliangruber** [comment]
working on:
- docs/es6.md
- docs/faq.md
- docs/index.md

**Comment by sotayamashita** [comment]
@fhemberger Still working?

**Comment by fhemberger** [comment]
@sotayamashita Unfortunately, no.
