### ISSUE TITLE
Translate 'io.js Week of February 6th 2015'

### ISSUE THREAD

**Issue by ghost** [iojs/iojs-de#7]
#1

https://medium.com/node-js-javascript/io-js-week-of-february-6th-2015-e185388549a4

question is where to publish our german translation?

**Comment by fhemberger** [comment]
We should set up GitHub pages for this repo with jekyll, see https://pages.github.com/

**Comment by ghost** [comment]
gh-pages created

**Comment by AlexZeitler** [comment]
Just registered io-js.de (iojs.de was already taken), so we can CNAME the GH-pages (+1 btw).

**Comment by fhemberger** [comment]
@alex Nice, but maybe we should talk to @mikeal if everybody is supposed to set up an own domain for the translation or if there will be something like iojs.org/de/ later on.

BTW: I just set up a Jekyll blog in the `gh-pages` branch and copied the original english post there. Does someone have a few minutes to translate the content? Please drop a short note here before you start so we don't do the work several times in parallel without knowing. ;) I think this is the best way to handle translations of new texts.

You can see the current version at http://iojs.github.io/iojs-de/

**Comment by ghost** [comment]
ok, i created a branch to start translation.

**Comment by ghost** [comment]
With commit #12 I would like to close this issue.

**Comment by timaschew** [comment]
> @alex Nice, but maybe we should talk to @mikeal if everybody is supposed to set up an own domain for the translation or if there will be something like iojs.org/de/ later on.

:+1:

**Comment by ghost** [comment]
@fhemberger we have the freedom of choice - almost.
Starting with this post https://github.com/iojs/website/issues/125#issuecomment-73437393 
Followed by this instruction https://github.com/iojs/website/blob/master/TRANSLATION.md

I think its up on us what we wanna do. translations of iojs.org will be under isjs.org/de if i understood it correctly. all the other stuff like collection of german io.js resources, meetup calenders, etc can be hosted on independent url.

**Comment by ktallett** [comment]
@fibric That seems to be the case. 

I have a few thoughts on it. 

So we need to build our own site. I think mobile first is best. Are we looking to keep updating over time? If so would a blog style be best for our needs? 

I was thinking about resources we can include.

-conference talks
-news
-tutorials (wrote by ourselves, translated)
-interviews(translated by ourselves, native speakers)

Any more ideas on resources or anything?

**Comment by timaschew** [comment]
> @fhemberger we have the freedom of choice - almost.
> Starting with this post iojs/website#125 (comment) 
> Followed by this instruction https://github.com/iojs/website/blob/master/TRANSLATION.md

Okay, didn't see the info before, so it makes sense :)
